import type { Metadata } from "next";
import "./style/globals.css";
import "./style/prism.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={'w-full h-full'} lang="zh">
      <body className={'w-full h-full overflow-hidden'}>
        {children}
      </body>
    </html>
  );
}
